# See https://pub.dev/packages/mono_repo for details on this file
sdk:
- 2.12.0
- dev

stages:
- analyze_and_format:
  - group:
    - format
    - analyze: --fatal-infos .
    sdk: dev
- unit_test:
  - command: dart run build_runner build example --fail-on-severe --delete-conflicting-outputs
  - command:
    - pushd ../_shared_assets
    - dart pub get
    - dart create_config.dart
    - popd
    - dart test

cache:
  directories:
  - .dart_tool/build
